### ISSUE TITLE
ur uh wizardex wizards spell engine power stuff breaks marium soulslike weaponry

### ISSUE THREAD

**Issue by Boroso** [ZsoltMolnarrr/SpellEngine#13]
ur uh wizardex wizards spell engine power stuff breaks marium soulslike weaponry right click ability such as spear thing n etc

**Comment by ZsoltMolnarrr** [comment]
`config/spell_engine/server.json5` set `add_spell_casting_to_swords` to `false`

**Comment by Boroso** [comment]
why not just add a whitelist and or blacklist to that instead of completely disabling it
